### PR TITLE
Add a Codacy badge to readme.md

### PR DESCRIPTION
**Pull request by codacy-badger**

### CODE REVIEW

**Comment by LarryHsiao** [comment]
don`t manually, issue closed

**Comment by 0pdd** [comment]
@codacy-badger the puzzle [#3](https://github.com/LarryHsiao/Nyx/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@codacy-badger 2 puzzles [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5) are still not solved.

**Comment by 0pdd** [comment]
@codacy-badger the puzzle [#7](https://github.com/LarryHsiao/Nyx/issues/7) is still not solved.

**Comment by 0pdd** [comment]
@codacy-badger 3 puzzles [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5) are still not solved.

**Comment by 0pdd** [comment]
@codacy-badger 4 puzzles [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5) are still not solved.

**Comment by 0pdd** [comment]
@codacy-badger the only puzzle [#7](https://github.com/LarryHsiao/Nyx/issues/7) is solved here.

**Comment by 0pdd** [comment]
@codacy-badger 3 puzzles [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#5](https://github.com/LarryHsiao/Nyx/issues/5) are still not solved; solved: [#3](https://github.com/LarryHsiao/Nyx/issues/3).

**Comment by 0pdd** [comment]
@codacy-badger the puzzle [#20](https://github.com/LarryHsiao/Nyx/issues/20) is still not solved; solved: [#7](https://github.com/LarryHsiao/Nyx/issues/7).

**Comment by 0pdd** [comment]
@codacy-badger 2 puzzles [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#5](https://github.com/LarryHsiao/Nyx/issues/5) are still not solved; solved: [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#3](https://github.com/LarryHsiao/Nyx/issues/3).

**Comment by 0pdd** [comment]
@codacy-badger all 2 puzzles are solved here: [#20](https://github.com/LarryHsiao/Nyx/issues/20), [#7](https://github.com/LarryHsiao/Nyx/issues/7).

**Comment by 0pdd** [comment]
@codacy-badger all 4 puzzles are solved here: [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 5 puzzles [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132) are still not solved; solved: [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 4 puzzles [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132) are still not solved; solved: [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 4 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#150](https://github.com/LarryHsiao/Nyx/issues/150) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 8 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 7 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 9 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#210](https://github.com/LarryHsiao/Nyx/issues/210), [#211](https://github.com/LarryHsiao/Nyx/issues/211) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 8 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#210](https://github.com/LarryHsiao/Nyx/issues/210) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#211](https://github.com/LarryHsiao/Nyx/issues/211), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 10 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#210](https://github.com/LarryHsiao/Nyx/issues/210), [#216](https://github.com/LarryHsiao/Nyx/issues/216), [#217](https://github.com/LarryHsiao/Nyx/issues/217) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#211](https://github.com/LarryHsiao/Nyx/issues/211), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 8 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#216](https://github.com/LarryHsiao/Nyx/issues/216), [#217](https://github.com/LarryHsiao/Nyx/issues/217) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#210](https://github.com/LarryHsiao/Nyx/issues/210), [#211](https://github.com/LarryHsiao/Nyx/issues/211), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 7 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#216](https://github.com/LarryHsiao/Nyx/issues/216) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#210](https://github.com/LarryHsiao/Nyx/issues/210), [#211](https://github.com/LarryHsiao/Nyx/issues/211), [#217](https://github.com/LarryHsiao/Nyx/issues/217), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger 8 puzzles [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#216](https://github.com/LarryHsiao/Nyx/issues/216), [#256](https://github.com/LarryHsiao/Nyx/issues/256) are still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#210](https://github.com/LarryHsiao/Nyx/issues/210), [#211](https://github.com/LarryHsiao/Nyx/issues/211), [#217](https://github.com/LarryHsiao/Nyx/issues/217), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Comment by 0pdd** [comment]
@codacy-badger the puzzle [#256](https://github.com/LarryHsiao/Nyx/issues/256) is still not solved; solved: [#126](https://github.com/LarryHsiao/Nyx/issues/126), [#128](https://github.com/LarryHsiao/Nyx/issues/128), [#130](https://github.com/LarryHsiao/Nyx/issues/130), [#131](https://github.com/LarryHsiao/Nyx/issues/131), [#132](https://github.com/LarryHsiao/Nyx/issues/132), [#150](https://github.com/LarryHsiao/Nyx/issues/150), [#161](https://github.com/LarryHsiao/Nyx/issues/161), [#166](https://github.com/LarryHsiao/Nyx/issues/166), [#167](https://github.com/LarryHsiao/Nyx/issues/167), [#168](https://github.com/LarryHsiao/Nyx/issues/168), [#169](https://github.com/LarryHsiao/Nyx/issues/169), [#16](https://github.com/LarryHsiao/Nyx/issues/16), [#170](https://github.com/LarryHsiao/Nyx/issues/170), [#19](https://github.com/LarryHsiao/Nyx/issues/19), [#210](https://github.com/LarryHsiao/Nyx/issues/210), [#211](https://github.com/LarryHsiao/Nyx/issues/211), [#216](https://github.com/LarryHsiao/Nyx/issues/216), [#217](https://github.com/LarryHsiao/Nyx/issues/217), [#3](https://github.com/LarryHsiao/Nyx/issues/3), [#5](https://github.com/LarryHsiao/Nyx/issues/5).

**Pull request closed without merging**
