### PR TITLE
Map improve

### PR DESCRIPTION
**Pull request by LarryHsiao**

### CODE REVIEW

**Comment by LarryHsiao** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/com/larryhsiao/nyx/android/LocationString.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/LarryHsiao/Nyx/pullRequest?prid=5090864&bid=16746582)

**Comment by LarryHsiao** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/com/larryhsiao/nyx/android/LocationString.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/LarryHsiao/Nyx/pullRequest?prid=5090864&bid=16746582)

**Comment by LarryHsiao** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/com/larryhsiao/nyx/android/LocationString.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/LarryHsiao/Nyx/pullRequest?prid=5090864&bid=16746582)

**Comment by 0pdd** [comment]
@LarryHsiao the puzzle [#258](https://github.com/LarryHsiao/Nyx/issues/258) is still not solved.

**Comment by 0pdd** [comment]
@LarryHsiao the only puzzle [#258](https://github.com/LarryHsiao/Nyx/issues/258) is solved here.

**Comment by 0pdd** [comment]
@LarryHsiao the puzzle [#288](https://github.com/LarryHsiao/Nyx/issues/288) is still not solved; solved: [#258](https://github.com/LarryHsiao/Nyx/issues/258).

**Comment by 0pdd** [comment]
@LarryHsiao 2 puzzles [#288](https://github.com/LarryHsiao/Nyx/issues/288), [#290](https://github.com/LarryHsiao/Nyx/issues/290) are still not solved; solved: [#258](https://github.com/LarryHsiao/Nyx/issues/258).

**Pull request merged**
